baseURL = "https://alopezespino.github.io/public/"
languageCode = "en-us"
title = "Alejandra Lopez Espino"
theme = "avicenna"
googleAnalytics = ""
timeout=3000

[params]
  subtitle= "PhD Student"
  interests="international trade, applied econometrics and computational analysis."
  cv_name= "CV_ALE_en_june2020.pdf"

[[params.affilation]]
  name = "Pennsylvania State University"
  position = "PhD Student"
  contact = "axl5463@psu.edu"

[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/alopezespino"

  [[params.introduction.paragraph]]
  text="""My research focuses on modelling and estimation of endogenous production networks. To do so, I combine recent developments the trade and matching literatures with semi-parametric identification and computational methods.
   """
[[params.projects]]
 [[params.projects.project]]
                name = "Endogenizing production networks"
                description  = "Abstract and draft coming soon"

 [[params.projects.project]]
                name = "Endogenous Production Networks: Identifying the value of firm-to-firm linkages"
                description  = "Abstract and draft coming soon"

[[params.projects.project]]
                name = "Characterizing the Mexican production network"
                description  = "Abstract coming soon"
